services:
  tendaelectronica:
    container_name: tendaelectronica2
    # usamos esta imagen para poder ver los logs
    # la imagen de internetsystemsconsortium/bind9
    # no muestra los logs
    image: ubuntu/bind9
    # especificamos la plataforma de la imagen
    # es posible conflicto cuando el host es 'arm'
    # ya que no existe una imagen para esa plataforma
    platform: linux/amd64
    ports:
      - 54:53
    networks:
      tenda_subnet:
        ipv4_address: 172.16.0.1
    volumes:
      - ./conf:/etc/bind
      - ./zonas:/var/lib/bind
  cliente:
    container_name: cliente3
    image: ubuntu/bind9
    platform: linux/amd64
    tty: true
    stdin_open: true
    # configuramos para que el cliente use nuestro dns
    dns:
      - 172.16.0.1
    networks:
      tenda_subnet:
        ipv4_address: 172.16.0.2
    
networks:
  tenda_subnet:
    external: true


